[package]
name = "dlgui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.0"
egui = "0.32.0"
env_logger = "0.11.8"
log = "0.4.27"
prost = "0.14.1"
rfd = "0.15.4"

[build-dependencies]
prost-build = "0.14.1"
